### PR TITLE
Add klaus.1 manpage.

### PR DESCRIPTION
**Pull request by jelmer**
Not sure if you care about manpages, but if you do - here is one :)

### CODE REVIEW

**Comment by jonashaag** [comment]
Cool! Thanks for the patch! I do care for man pages, but I'm not sure how well they integrate with the Python packaging system? Are they made accessible from `man klaus` if installed in `/usr/lib/pythonX.Y/...` (or similar)? They're most certainly not accessible if installed in a virtualenv?

Btw, I think we should be using something like https://github.com/oz123/man-utils to avoid documentation duplication. I never used *man-utils* but it looks promising.

**Comment by jelmer** [comment]
On Wed, Dec 09, 2015 at 12:58:39AM -0800, Jonas Haag wrote:
> Cool! Thanks for the patch! I do care for man pages, but I'm not sure how well they integrate with the Python packaging system? Are they made accessible from `man klaus` if installed in `/usr/lib/pythonX.Y/...` (or similar)? They're most certainly not accessible if installed in a virtualenv?
> 
> Btw, I think we should be using something like https://github.com/oz123/man-utils to avoid documentation duplication. I never used *man-utils* but it looks promising.
If you'd like to avoid shipping a troff file, what about just using
docutils' rst2man ? See
http://docutils.sourceforge.net/sandbox/manpage-writer/rst2man.txt

I'm adding the manpage for Debian, and man-utils doesn't appear to be
packaged in Debian yet.

Jelmer

**Comment by jonashaag** [comment]
> I'm adding the manpage for Debian, and man-utils doesn't appear to be
> packaged in Debian yet.

Hm. It's not about shipping a troff file. It's about not repeating yourself w.r.t. the CLI options, and potentially missing updates if a command-line argument is changed. For the time being, it should be ok to add a note to `RELEASE_PROCESS`.

**Comment by jonashaag** [comment]
There seems to be a missing closing parenthesis in the description: `\(tm` or does this have some other special meaning?

**Comment by jelmer** [comment]
On Thu, Dec 10, 2015 at 01:49:19AM -0800, Jonas Haag wrote:
> There seems to be a missing closing parenthesis in the description: `\(tm` or does this have some other special meaning?
Yes, that's intentional - troff formats this a small supercase "TM".

Jelmer

**Pull request merged**
