### PR TITLE
Stop appending "No new line at end of file" warning for each changed …

### PR DESCRIPTION
**Pull request by alekseyrybalkin**
…line of a diff

### CODE REVIEW

**Comment by jonashaag** [comment]
This is on purpose, but I'm happy to discuss other visualisations of that information, maybe with a return symbol and a tooltip, see: https://github.com/yiisoft/yii2/pull/122/files

**Comment by alekseyrybalkin** [comment]
The problem is this icon shows for _every_ changed line (old and new), even if the filea ctually _has_ a new line at the end of file. E.g.: http://git.rybalkin.org/kiin-repo/commit/011be0cd1124155650f5b3d335d8f2a8441c61c9/

After this patch, the icon shows only if the end of file is in the diff and if there is actually no new line at the end of file.

**Comment by jonashaag** [comment]
Oh, I see. Thanks!

**Comment by jonashaag** [comment]
Your patch wasn't correct, I fixed it along with another TODO.

**Comment by alekseyrybalkin** [comment]
Great, thanks!

**Comment by sbraz** [comment]
@jonashaag is this supposed to remove the pretty inline highlights? `highlight_line` is not called any more, sounds like a regression to me.

**Comment by jonashaag** [comment]
Whoops, yes.

**Pull request closed without merging**
