### PR TITLE
Add an 'index' page that displays a bit of history and README.

### PR DESCRIPTION
**Pull request by jelmer**
This implements https://github.com/jonashaag/klaus/issues/167.

### CODE REVIEW

**Comment by jonashaag** [comment]
So cool! Thanks a lot!

One minor thing though, where would the `/history/` URL be used? I haven't seen it while playing around with klaus; it seems redundant.

**Comment by jelmer** [comment]
(The test failure is python2.6-specific and seems to be in one of the dependencies, unrelated to my change).

The history page is still what's linked in other places - it doesn't display the README doc. The index page also links to the history page (without README) if you click on "Next page".

**Comment by jonashaag** [comment]
Yes but it never links to this specific rule `('history',     '/<repo>/history')`, does it?

**Comment by jelmer** [comment]
Ah, I see what you mean. No, that's true.

**Comment by jonashaag** [comment]
Merged, thanks a lot!

**Comment by PeterDaveHello** [comment]
Is it possible to add an option to decide display it or not? This feature is awesome 👍

**Comment by jonashaag** [comment]
Sure, but why would you want that?

**Comment by PeterDaveHello** [comment]
Just be too familiar with the origin style 😅 thanks

**Comment by jonashaag** [comment]
Haha ok, then I suggest you make a fork of klaus and change the `'index'` route to `'history'` everywhere in the code (should be only a handful places).

**Pull request merged**
