### PR TITLE
Add ProxyFix, deprecate SubUri (incorrect behavior)

### PR DESCRIPTION
**Pull request by jonashaag**
@jelmer Please try this; note that `X-Scheme` has been changed to the de facto standard `X-Forwarded-Proto`. (Although there seems to be RFC 7239 with the `Forwarded` header, see mitsuhiko/werkzeug#800)

### CODE REVIEW

**Comment by jonashaag** [comment]
Would also be great if we had a few tests for this.

**Comment by jelmer** [comment]
On Sun, Nov 08, 2015 at 03:26:04PM -0800, Jonas Haag wrote:
> @jelmer Please try this; note that `X-Scheme` has been changed to the de facto standard `X-Forwarded-Proto`. (Although there seems to be RFC 7239 with the `Forwarded` header...)
> You can view, comment on, or merge this pull request online at:
Thanks, I'll take some time this week to test it.

**Comment by jonashaag** [comment]
bump

**Comment by jelmer** [comment]
On Sun, Nov 08, 2015 at 03:26:04PM -0800, Jonas Haag wrote:
> @jelmer Please try this; note that `X-Scheme` has been changed to the de facto standard `X-Forwarded-Proto`. (Although there seems to be RFC 7239 with the `Forwarded` header...)
> You can view, comment on, or merge this pull request online at:
Yep, I can confirm it still works with this branch.

Jelmer

**Comment by jonashaag** [comment]
Thanks!

**Pull request merged**
