### PR TITLE
Default to running Klaus in Python3

### PR DESCRIPTION
**Pull request by jelmer**
Default to running Klaus in Python3.

### CODE REVIEW

**Comment by jonashaag** [comment]
Hmmm shouldn't `python` be an alias to `python3` on modern systems?

Can we be sure that `python3` exists?

**Comment by jelmer** [comment]
All python 3 installations provide a python3 binary - but on e.g. the last release of Debian python often still points at python2.

This PR is motivated by the fact that I keep invoking bin/klaus on my Debian Sid machine and having it fail because newer versions of dulwich are python3 only.

**Comment by jelmer** [comment]
See also https://www.python.org/dev/peps/pep-0394/

**Comment by jonashaag** [comment]
Thanks!

**Pull request merged**
