### PR TITLE
Disable GPG signing during tests.

### PR DESCRIPTION
**Pull request by jelmer**

### CODE REVIEW

**Comment by jonashaag** [comment]
What use is this?

**Comment by jelmer** [comment]
On Sun, Nov 01, 2015 at 12:02:19PM -0800, Jonas Haag wrote:
> What use is this?
I've got GPG signing enabled by default in my Git configuration, which makes
running the Klaus testsuite painful as I have to manuall approve each GPG
signature.

Jelmer

**Comment by jonashaag** [comment]
I think we should rather set `commit.gpgSign` in the repo's config

**Comment by jelmer** [comment]
On Sun, Nov 01, 2015 at 02:41:41PM -0800, Jonas Haag wrote:
> I think we should rather set `commit.gpgSign` in the repo's config
Ideally, just set a custom user config so that configuration from
$HOME/.gitconfig doesn't leak through in the tests.

**Comment by jonashaag** [comment]
Right!

**Pull request merged**
