### PR TITLE
python 3.12 support

### PR DESCRIPTION
**Pull request by fin444**
remove references to distutils
- `app_args.py`: add polyfill
- `setup.py`: remove code that hasn't been necessary since 51094d7

### CODE REVIEW

**Comment by jonashaag** [comment]
Thanks for the patch! Do you think you know what you're doing here? Because I don't when it comes to these packaging things and have no way of verifying because I have no clue what's right and wrong. So I'll have to trust your judgment here.

**Comment by jelmer** [comment]
FWIW this looks good to me.

**Comment by fin444** [comment]
I'm not exactly an expert on this, but for `app_args.py` it's just copy pasting the function from the library. For `setup.py`, what I found suggested that the hack was only necessary if `data_files` was included as a parameter ([source 1](https://stackoverflow.com/a/3042436), [source 2](https://github.com/celery/kombu/pull/1467#pullrequestreview-849763856), source 3 it just says it in the comment)

**Comment by fin444** [comment]
And while clean up would be cool, I don't know much about packaging lol. I only submitted this because NixOS updated to 3.12 and it broke my stuff

**Pull request merged**
