### PR TITLE
Fix import of ProxyFix for Werkzeug 1.0.0

### PR DESCRIPTION
**Pull request by embeddedc**
Fix import of ProxyFix for werkzeug 1.0.x

### CODE REVIEW

**Comment by jonashaag** [comment]
Is this also compatible with older versions of Werkzeug? Otherwise we’d have to specify minimum version in requirements.

**Comment by embeddedc** [comment]
`werkzeug.middleware.proxy_fix` has been introduced with `werkzeug 0.15.0`, so that would be the minimum version.

`pip install klaus `will currently import `werkzeug 1.0.0`, so everybody will get a `No module named 'werkzeug.contrib'` error

**Comment by jonashaag** [comment]
<3

**Comment by embeddedc** [comment]
Danke nach 
😊

**Pull request merged**
